/*********************************************************/
/* Author    :Hagar tarek & Panssee mahmoud              */
/* SWC       :SYSTICK                   			     */
/* Layer     :MCAL                        				 */
/* Version   :1.0                         				 */
/* Date      :October 17, 2023            				 */
/* Last Edit :N/A                         				 */
/*********************************************************/

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "SYSTICK_config.h"
#include "SYSTICK_interface.h"
#include "SYSTICK_private.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */


/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ------------------------------------*/
/* USER CODE BEGIN PV */
u16 u16Data[100] = {0};
u32 u32Address = 0x08000000;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */

/** Define Callback Global Variable */
static void(*SYSTICK_CallBack)(void);

/** Define Variable for interval mode */
static u8 u8ModeOfInterval;
/* USER CODE END PFP */

/**
  * @brief  Initialize the SysTick timer.
  * @param  None
  * @note   This function configures the SysTick timer based on the selected clock source
  *         and initializes necessary variables.
  * @return None
  */

void SYSTICK_voidInit(void)
{
#if SYSTICK_CLK_SRC == SYSTICK_SRC_AHB
    /* Disable STK - Disable STK Interrupt - Set clock source AHB */
	SYSTICK -> CTRL = 0x00000004;
#else
    /* Disable STK - Disable STK Interrupt - Set clock source AHB/8 */
	SYSTICK -> CTRL = 0;
#endif
}

/**
  * @brief  Implement a busy-wait delay using the SysTick timer.
  * @param  Copy_u32Ticks: Number of ticks to wait.
  * @note   This function uses the SysTick timer to create a busy-wait delay.
  * @return None
  */
void SYSTICK_voidSetBusyWait( u32 Copy_u32Ticks )
{
	/* Load ticks to load register */
	SYSTICK -> LOAD = Copy_u32Ticks;
	/* Start Timer */
	SETBIT(SYSTICK->CTRL, 0);
	/* Wait till flag is raised */
	while( (GET_BIT(SYSTICK->CTRL,16)) == 0);
	/* Stop Timer */
	CLR_BIT(SYSTICK->CTRL, 0);
	SYSTICK -> LOAD = 0;
	SYSTICK -> VAL  = 0;
}


/**
  * @brief  Set a single-shot interval using the SysTick timer.
  * @param  Copy_u32Ticks: Number of ticks for the interval.
  * @param  Copy_ptr: Pointer to the callback function.
  * @note   This function configures the SysTick timer to generate a single-shot
  *         interval and associates a callback function to be executed when the
  *         interval elapses.
  * @return None
  */
void SYSTICK_voidSetIntervalSingle  ( u32 Copy_u32Ticks, void (*Copy_ptr)(void) )
{
	/* Stop Timer */
	CLR_BIT(SYSTICK->CTRL, 0);
	SYSTICK -> LOAD = 0;
	SYSTICK -> VAL  = 0;
	/* Load ticks to load register */
	SYSTICK -> LOAD = Copy_u32Ticks;
	/* Start Timer */
	SETBIT(SYSTICK->CTRL, 0);
	/* Save CallBack */
	SYSTICK_CallBack = Copy_ptr;
	/* Set Mode to Single */
	u8ModeOfInterval = SYSTICK_SINGLE_INTERVAL;
	/* Enable STK Interrupt */
	SETBIT(SYSTICK->CTRL, 1);
}

/**
  * @brief  Set a periodic interval using the SysTick timer.
  * @param  Copy_u32Ticks: Number of ticks for the interval.
  * @param  Copy_ptr: Pointer to the callback function.
  * @note   This function configures the SysTick timer to generate a periodic
  *         interval and associates a callback function to be executed at each
  *         interval.
  * @return None
  */
void SYSTICK_voidSetIntervalPeriodic( u32 Copy_u32Ticks, void (*Copy_ptr)(void) )
{
	/* Load ticks to load register */
	SYSTICK -> LOAD = Copy_u32Ticks;
	/* Start Timer */
	SETBIT(SYSTICK->CTRL, 0);
	/* Save CallBack */
	SYSTICK_CallBack = Copy_ptr;
	/* Set Mode to Single */
	u8ModeOfInterval = SYSTICK_PERIOD_INTERVAL;
	/* Enable STK Interrupt */
	SETBIT(SYSTICK->CTRL, 1);
}

/**
  * @brief  Stop the ongoing interval generated by the SysTick timer.
  * @param  None
  * @note   This function disables the SysTick interrupt and stops the timer.
  * @return None
  */
void SYSTICK_voidStopInterval(void)
{
	/* Disable STK Interrupt */
	CLR_BIT(SYSTICK->CTRL, 1);
	/* Stop Timer */
	SETBIT(SYSTICK->CTRL, 0);
	SYSTICK -> LOAD = 0;
	SYSTICK -> VAL  = 0;
}


/**
  * @brief  Get the elapsed time since the last SysTick interrupt.
  * @param  None
  * @return The elapsed time in ticks.
  */
u32  SYSTICK_u32GetElapsedTime(void)
{
	u32 Local_u32ElapsedTime;
	Local_u32ElapsedTime = (SYSTICK -> LOAD) - (SYSTICK -> VAL) ;
	return Local_u32ElapsedTime;
}

/**
  * @brief  Get the remaining time for the next SysTick interrupt.
  * @param  None
  * @return The remaining time in ticks.
  */
u32  SYSTICK_u32GetRemainingTime(void)
{
	u32 Local_u32RemainTime;
	Local_u32RemainTime = SYSTICK -> VAL ;
	return Local_u32RemainTime;
}

