/*********************************************************/
/* Author    : Hagar tarek & Panssee mahmoud             */
/* SWC       : SYSTICK                   			     */
/* Layer     : MCAL                        				 */
/* Version   : 1.0                         				 */
/* Date      : October 17, 2023            				 */
/* Last Edit : N/A                         				 */
/*********************************************************/

#ifndef _SYSTICK_INTERFACE_H_
#define _SYSTICK_INTERFACE_H_

/**
 * @brief Initialize the SysTick timer.
 * @note This function configures the SysTick timer based on the selected clock source
 *       and initializes necessary variables.
 * @return None
 */
void SYSTICK_voidInit(void);

/**
 * @brief Implement a busy-wait delay using the SysTick timer.
 * @param Copy_u32Ticks: Number of ticks to wait.
 * @note This function uses the SysTick timer to create a busy-wait delay.
 * @return None
 */
void SYSTICK_voidSetBusyWait(u32 Copy_u32Ticks);

/**
 * @brief Set a single-shot interval using the SysTick timer.
 * @param Copy_u32Ticks: Number of ticks for the interval.
 * @param Copy_ptr: Pointer to the callback function.
 * @note This function configures the SysTick timer to generate a single-shot
 *       interval and associates a callback function to be executed when the
 *       interval elapses.
 * @return None
 */
void SYSTICK_voidSetIntervalSingle(u32 Copy_u32Ticks, void (*Copy_ptr)(void));

/**
 * @brief Set a periodic interval using the SysTick timer.
 * @param Copy_u32Ticks: Number of ticks for the interval.
 * @param Copy_ptr: Pointer to the callback function.
 * @note This function configures the SysTick timer to generate a periodic
 *       interval and associates a callback function to be executed at each
 *       interval.
 * @return None
 */
void SYSTICK_voidSetIntervalPeriodic(u32 Copy_u32Ticks, void (*Copy_ptr)(void));

/**
 * @brief Stop the ongoing interval generated by the SysTick timer.
 * @note This function disables the SysTick interrupt and stops the timer.
 * @return None
 */
void SYSTICK_voidStopInterval(void);

/**
 * @brief Get the elapsed time since the last SysTick interrupt.
 * @return The elapsed time in ticks.
 */
u32 SYSTICK_u32GetElapsedTime(void);

/**
 * @brief Get the remaining time for the next SysTick interrupt.
 * @return The remaining time in ticks.
 */
u32 SYSTICK_u32GetRemainingTime(void);

#endif

/** @} */

